"""Transparency label rendering — maps a (verdict, confidence) to reader-facing text.

Exactly three variants (planning.md §3), mirrored verbatim in the README. Each one names the
outcome in plain language, states the confidence as a whole-number percent, and frames itself as
an estimate rather than a verdict. The two fallible outcomes (AI, uncertain) both point to the
appeal path. The label changes with the verdict — it is never the same text regardless of score.
"""

from __future__ import annotations

# verdict -> (variant id, template). {pct} is filled with the confidence as a whole-number percent.
_LABELS = {
    "ai": (
        "high_confidence_ai",
        "🤖 Likely AI-generated. Provenance Guard's analysis strongly suggests this was produced "
        "with generative AI ({pct}% confidence). This is an automated estimate, not a certainty — "
        "if you're the creator and disagree, you can appeal.",
    ),
    "human": (
        "high_confidence_human",
        "✍️ Likely human-written. Provenance Guard's analysis strongly suggests a person wrote "
        "this ({pct}% confidence). This is an automated estimate, not a certainty.",
    ),
    "uncertain": (
        "uncertain",
        "🤔 Origin unclear. Provenance Guard could not confidently determine whether this was "
        "written by a person or generated by AI ({pct}% confidence). Treat this as inconclusive. "
        "If you're the creator, you can add context by appealing.",
    ),
}


def render_label(verdict: str, confidence: float) -> dict[str, str]:
    """Return ``{"variant", "text"}`` for the given verdict, with confidence as a percent.

    ``verdict`` must be one of ``ai`` / ``human`` / ``uncertain`` (the values from
    ``scoring.fuse``). Unknown verdicts fall back to the ``uncertain`` variant defensively.
    """
    variant, template = _LABELS.get(verdict, _LABELS["uncertain"])
    return {"variant": variant, "text": template.format(pct=round(confidence * 100))}
