"""Signal 1 — LLM semantic judge (Groq ``llama-3.3-70b-versatile``).

Asks a large model for a holistic read on whether a passage was written by a person or
generated by AI, returned as a probability ``p_ai`` plus a one-line rationale.

Design notes (see planning.md §1):
- The model is the *higher-weighted* signal in M4 fusion but must never be treated as ground
  truth — it is biased toward flagging polished/formal human writing as AI.
- We ask for strict JSON, parse defensively, **retry once** on malformed output, and on
  persistent failure fall back to a non-committal ``p_ai = 0.5`` so the (future) fusion step
  reads it as low-information rather than a confident vote.
"""

from __future__ import annotations

import json
import os
from typing import Any

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

# Probability of AI authorship used when we cannot get a usable answer from the model.
# 0.5 = "no information" by design — it must not nudge a verdict either way.
_FALLBACK_P_AI = 0.5

_SYSTEM_PROMPT = (
    "You are a forensic writing analyst estimating whether a passage was written by a human "
    "or generated by an AI language model. Judge holistically: coherence, specificity, voice, "
    "idiomatic risk-taking, and concrete personal detail. AI prose tends to be fluent but "
    "generic, evenly hedged, and structurally balanced; human prose takes more idiosyncratic "
    "risks and varies in quality. Be calibrated and cautious: polished or formal writing is NOT "
    "by itself evidence of AI, and non-native-English writing is often human.\n\n"
    "Calibrate across the FULL 0-1 range: when the evidence clearly points one way, commit to a "
    "value near the extreme (>= 0.9 for text that is obviously AI-generated, <= 0.1 for text that "
    "is obviously human); reserve values near 0.5 for genuinely ambiguous cases. Do not cluster "
    "around 0.7-0.8 when you are actually confident.\n\n"
    'Respond with ONLY a JSON object of exactly this shape: '
    '{"p_ai": <number between 0 and 1>, "rationale": "<one short sentence>"}. '
    "p_ai is the probability the text is AI-generated (1 = certainly AI, 0 = certainly human)."
)

_client: Groq | None = None


def _get_client() -> Groq:
    """Lazily construct the Groq client so importing this module never requires a key."""
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set; cannot call the LLM judge.")
        _client = Groq(api_key=api_key)
    return _client


def _call_model(text: str) -> str:
    """One Groq chat-completion call. Returns the raw message content string."""
    resp = _get_client().chat.completions.create(
        model=MODEL,
        temperature=0,  # deterministic-as-possible for stability across runs
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this passage and return JSON:\n\n{text}"},
        ],
    )
    return resp.choices[0].message.content or ""


def _parse(raw: str) -> dict[str, Any] | None:
    """Parse the model's JSON into a clamped ``{p_ai, rationale}`` dict, or None if malformed."""
    try:
        data = json.loads(raw)
        p_ai = float(data["p_ai"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        return None
    p_ai = max(0.0, min(1.0, p_ai))  # clamp into [0, 1]
    rationale = str(data.get("rationale", "")).strip() or "(no rationale provided)"
    return {"p_ai": p_ai, "rationale": rationale}


def score_llm(text: str) -> dict[str, Any]:
    """Score ``text`` with the LLM judge.

    Returns ``{"signal": "llm", "p_ai": float, "rationale": str}``. Never raises: on a model
    or parse failure it returns the non-committal fallback (``p_ai = 0.5``) with a rationale
    naming the failure mode (``parse_failed`` / ``llm_error``).
    """
    # Two attempts: a transient bad-JSON response should not sink the request.
    for _ in range(2):
        try:
            raw = _call_model(text)
        except Exception as exc:  # noqa: BLE001 — any API/network/auth error → graceful fallback
            return {"signal": "llm", "p_ai": _FALLBACK_P_AI, "rationale": f"llm_error: {exc}"}
        parsed = _parse(raw)
        if parsed is not None:
            return {"signal": "llm", **parsed}

    return {"signal": "llm", "p_ai": _FALLBACK_P_AI, "rationale": "parse_failed"}
